# Generated by Django 3.0.7 on 2022-01-02 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_staffprofile_is_employee_user_is_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('my_file', models.FileField(upload_to='')),
                ('post_share', models.CharField(max_length=1000)),
            ],
        ),
    ]
