# Generated by Django 4.0 on 2022-01-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='applyForRelief',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NID_No', models.CharField(max_length=17)),
                ('Name', models.CharField(max_length=20)),
                ('Distric', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Chittagong', 'Chittagong'), ('Rajshahi', 'Rajshahi'), ('Sylhet', 'Sylhet'), ('Mymensingh', 'Mymensingh'), ('Barisal', 'Barisal'), ('Rangpur', 'Rangpur'), ('Khulna', 'Khulna')], default='Dhaka', max_length=20)),
                ('Village', models.CharField(max_length=50)),
                ('Phone_no', models.CharField(max_length=11)),
                ('Birth_Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ComplainBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('NID_no', models.IntegerField()),
                ('email', models.CharField(max_length=150)),
                ('report', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='createOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10)),
                ('phone_number', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15)),
                ('Share_something', models.CharField(max_length=5000)),
                ('Phone_no', models.IntegerField(max_length=11)),
                ('Payment_Method', models.CharField(choices=[('Bkash', 'Bkash'), ('Nagad', 'Nagad'), ('DBBL', 'DBBL')], default='Bkash', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('my_file', models.FileField(upload_to='')),
                ('post_share', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.PositiveIntegerField()),
            ],
        ),
    ]
