# Generated by Django 4.0 on 2022-01-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheba', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyforrelief',
            name='ZIP_Code',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
