# Generated by Django 4.0 on 2022-01-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheba', '0002_applyforrelief_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyforrelief',
            name='ZIP_Code',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='donation',
            name='Phone_no',
            field=models.IntegerField(),
        ),
    ]
