# Generated by Django 4.0 on 2022-01-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheba', '0003_alter_applyforrelief_zip_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyforrelief',
            name='Marita_Status',
            field=models.CharField(choices=[('Married', 'Married'), ('Single', 'Single')], default='Single', max_length=10),
        ),
    ]
