# Generated by Django 4.0 on 2022-01-01 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheba', '0004_applyforrelief_marita_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applyforrelief',
            old_name='Marita_Status',
            new_name='Marital_Status',
        ),
    ]
