# Generated by Django 4.0 on 2022-01-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheba', '0005_rename_marita_status_applyforrelief_marital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyforrelief',
            name='code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
