# Generated by Django 4.0 on 2022-01-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheba', '0006_applyforrelief_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='Marital_Status',
            field=models.CharField(choices=[('Married', 'Married'), ('Single', 'Single')], default='Single', max_length=10),
        ),
    ]
