# Generated by Django 4.0 on 2022-01-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheba', '0007_donation_marital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='Area',
            field=models.CharField(choices=[('Dhaka', 'Dhaka'), ('Chittagong', 'Chittagong'), ('Rajshahi', 'Rajshahi'), ('Sylhet', 'Sylhet'), ('Mymensingh', 'Mymensingh'), ('Barisal', 'Barisal'), ('Rangpur', 'Rangpur'), ('Khulna', 'Khulna')], default='Dhaka', max_length=20),
        ),
    ]
